markdown: rdiscount
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: 
    - smart
    - generate_toc
redcarpet:
  extensions:
    - fenced_code_blocks
    - smart
    - strikethrough
    - no_intra_emphasis
    - with_toc_data
future: true
tag_dir: blog/tags
collections:
  recipes:
    output: true
    permalink: /recipes/:path/
defaults:
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      menu: "stream"

name: m. c. de marco
short_name: m.c.d.
url: http://mcdemarco.net
description: To invent new life and new civilizations...
twitter: mcdemarco
github: mcdemarco
gravatar_url: http://www.gravatar.com/avatar/412cc45595f0437c7fe69ade81e21a4a.png
exclude: [ToDo.md]