markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
auto: false
rdiscount:
  extensions: [smart]
future: true

name: m. c. de marco
short_name: m.c.d.
url: http://mcdemarco.net
description: To invent new life and new civilizations...
twitter: mcdemarco
github: mcdemarco
gravatar_url: http://www.gravatar.com/avatar/412cc45595f0437c7fe69ade81e21a4a.png